module.exports.poem = [
    "Anger",
    "Anime",
    "Blanket", 
    "Boop", 
    "Bouncy", 
    "Bubbles", 
    "Bunny",
    "Candy", 
    "Cheeks", 
    "Chocolate", 
    "Clouds", 
    "Cute",
    "Doki-Doki",
    "Email",
    "Fantasy",
    "Fluffy",
    "Games",
    "Giggle",
    "Hair",
    "Headphones", 
    "Heartbeat", 
    "Hop",
    "Jump",
    "Jumpy",
    "Kawaii",
    "Kiss", 
    "Kitty",
    "Lipstick",
    "Lollipop",
    "Marshmallow",
    "Melody",
    "Milk",
    "Mouse",
    "Nibble",
    "Nightgown",
    "Papa",
    "Parfait",
    "Peace",
    "Pink",
    "Playground",
    "Poof",
    "Pout",
    "Puppy",
    "Pure",
    "Ribbon",
    "Shiny",
    "Shopping",
    "Skipping",
    "Skirt",
    "Socks",
    "Spinning",
    "Sticky",
    "Strawberry",
    "Sugar",
    "Summer",
    "Swimsuit",
    "Twirl",
    "Valentine",
    "Vanilla",
    "Waterfall",
    "Whisper",
    "Whistle"
]

module.exports.baka = ["baka", "BAKA", "BAKa", "BAka", "Baka", "bAKA", "baKA", "bakA", "baKa", "bAka", "BakA", "bAKa", "BaKa", "bAkA"];

module.exports.becauseYou = [
    "My looking is a little more forward,\nBecause you look at me",
    "My words are a little less empty,\nBecause you listen to me",
    "My standing is a little bit taller,\nBecause you sit with me", 
    "My faith is a little bit stronger,\nBecause you trusted me.",
    "My poems are a little bit dearer,\nBecause you think of me." 
  ];

  module.exports.numberArray = [
    "Ugh fine... you're not gonna like it though. ```markdown\n# Amy Likes Spiders\n\nYou know what I heard about Amy?\nAmy likes spiders.\nIcky, wriggly, hairy, ugly spiders!\nThat's why I'm not friends with her.\n\nAmy has a cute singing voice.\nI heard her singing my favorite love song.\nEvery time she sang the chorus, my heart would pound to the rhythm of the words.\nBut she likes spiders.\nThat's why I'm not friends with her.\n\nOne time, I hurt my leg really bad.\nAmy helped me up and took me to the nurse.\nI tried not to let her touch me.\nShe likes spiders, so her hands are probably gross.\nThat's why I'm not friends with her.\n\nAmy has a lot of friends.\nI always see her talking to people.\nShe probably talks about spiders.\nWhat if her friends start to like spiders too?\nThat's why I'm not friends with her.\n\nIt doesn't matter if she has other hobbies.\nIt doesn't matter if she keeps it private.\nIt doesn't matter if it doesn't hurt anyone.\n\nIt's gross.\nShe's gross.\nThe world is better off without spider lovers.\n\nAnd I'm gonna tell everyone.```",
    "I didn't write this for ***you***... God you're so self centred. ```markdown\n# Because You\n\nTomorrow will be brighter with me around\nBut when today is dim, I can only look down.\nMy looking is a little more forward\nBecause you look at me.\n\nWhen I want to say something, I say it with a shout!\nBut my truest feelings can never come out.\nMy words are a little less empty\nBecause you listen to me.\n\nWhen something is above me, I reach for the stars.\nBut when I feel small, I don't get very far.\nMy standing is a little bit taller\nBecause you sit with me.\n\nI believe in myself with all of my heart.\nBut what do I do when it's torn all apart?\nMy faith is a little bit stronger\nBecause you trusted me.\n\nMy pen always puts my feelings to the test.\nI'm not a good writer, but my best is my best.\nMy poems are a little bit dearer\nBecause you think of me.\n\nBecause you, because you, because you.```",
    "You'll hate this one... ```markdown\n# Eagles Can Fly\n\nMonkeys can climb\nCrickets can leap\nHorses can race\nOwls can seek\nCheetahs can run\nEagles can fly\nPeople can try\nBut that's about it.```", 
    "I don't write for anyone. Especially **not** you. ```markdown\n# I'll Be Your Beach\n\nYour mind is so full of troubles and fears\nThat diminished your wonder over the years\nBut today I have a special place\nA beach for us to go.\n\nA shore reaching beyond your sight\nA sea that sparkles with brilliant light\nThe walls in your mind will melt away\nBefore the sunny glow.\n\nI'll be the beach that washes your worries away\nI'll be the beach that you daydream about each day\nI'll be the beach that makes your heart leap\nIn a way you thought had left you long ago.\n\nLet's bury your heavy thoughts in a pile of sand\nBathe in sunbeams and hold my hand\nWash your insecurities in the salty sea\nAnd let me see you shine.\n\nLet's leave your memories in a footprint trail\nSet you free in my windy sail\nAnd remember the reasons you're wonderful\nWhen you press your lips to mine.\n\nI'll be the beach that washes your worries away\nI'll be the beach that you daydream about each day\nI'll be the beach that makes your heart leap\nIn a way you thought had left you long ago.\n\nBut if you let me by your side\nYour own beach, your own escape\nYou'll learn to love yourself again.```" 
  ];
